languageCode = "en"
languageName = "English"
weight = 1
title = "Andrea Cerfoglia"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Andrea Cerfoglia"
  image = "img/logo.png"
 # headline = "Computer Engineering student at Poitecnico di Milano""
  bio = "Computer Engineering student at Poitecnico di Milano, intrested in anything and everything that ticks or makes electron flow"
  links = [
  
  
    { github = "https://github.com/TheBigBoschi" },
  ]

  
