[[main]]
none = "none"

[[main]]
name = "Linux"
pageRef = "linux"
identifier = "QtC2VwhaVQ"
weight = 9_999

[[main]]
name = "Electronics"
pageRef = "electronics"
identifier = "X1T5Ai8nQV"
weight = 9_999

[[footer]]
none = "none"
