baseurl = "TheBigBoschi.github.io"
metaDataFormat = "yaml"
languageCode = "en-us"
title = "Andrea Cerfoglia's blog"
theme = ["blist"]

[params]

  introTitle = "Hey! I'm Andrea Cerfoglia!"
  introSubtitle = "22 yo tinkerer that loves to work with his hands! <br>Here you'll find a collection of my technical work and some other stuff too!"
  introPhoto = "/myPicture.png"
  logo = "/logo.png"
  
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Andrea Cerfoglia · All rights reserved"
  favicon = "/logo.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  #description = "I work on intresting stuff and "
  #twitter = "https://twitter.com/"
  #linkedin = "https://linkedin.com/in/"
  #xing = "https://www.xing.com/profile/"
  github = "https://github.com/TheBigBoschi"
  instagram = "https://www.instagram.com/boschi1999/"
  #medium = "https://medium.com/"
  #reddit = "https://reddit.com/"
  #dribbble = "https://dribbble.com/"
  #stackoverflow = "https://stackoverflow.com/"


[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

# Privacy section

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
